# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75e2d0dd9ccd11d55eb7f599be039fceedd8b6e6e3bb4ec96129503b49d22fa66f6b6c12eee6c4555b220b3300c89a953d69ad17ea639f811d6d9ead66666908

test:
  secret_key_base: 3258fd0af5332e84e1834f4d4fa3d2c9c9441d3a2c8358e8747ed2707bf30bbf6c93ec06ec917aaa4d920be07ebd1bee4db96c95b324299e619b1a2d82a2ba85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
